// Auto-generated by scripts/generate-firebase-config.mjs
// Do not hardcode private server secrets here. This file is shipped to browsers.
export const FIREBASE_WEB_CONFIG = {
  apiKey: "",
  authDomain: "",
  projectId: "monkey-typewriter",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
};
